image: ubuntu:14.04
  
upload_egg:
  script:
    # add git as part of the egg upload
    - apt-get update -y && apt-get install -y git
    # Check if the package is actually installable
    - apt-get install -y python curl
    - apt-get install -y python-dev libffi-dev
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    - python get-pip.py
    - pip install pyOpenSSL ndg-httpsclient pyasn1
    - pip install -U devpi-client
    - pip install .
    - pip show $CI_PROJECT_NAME
    
    # Upload to Wish Pypi
    - devpi use $PYPI_SERVER
    - devpi login $USERNAME --password=$PASSWORD
    - devpi use $INDEX
    - devpi upload
  only:
    - master
